SC-777 Don't fail if hook installation directory is not writable
spryker/git-hook pull request #32
Opened 2019-06-13 11:14 UTC by marek-obuchowicz

2019-06-13 11:23 UTC, stereomon requested changes

2019-06-13 11:23 UTC, stereomon commented on src/GitHook/Composer/Scripts/HookInstaller.php
> +        if (!self::checkDirectoryPermissions($gitHookDirectory, $event)) return true;
```
if (!self::checkDirectoryPermissions($gitHookDirectory, $event)) {
     return true;
}
```

For the other cases as well please.

2019-06-13 11:30 UTC, dereuromark commented
Fairly certain the fixer could fix this itself even ( https://travis-ci.org/spryker/git-hook/jobs/545184428 )

2019-06-13 11:36 UTC, marek-obuchowicz commented
@dereuromark :+1: thanks for onboarding into validations topic, that's still new for me

2019-06-14 08:45 UTC, stereomon approved these changes
Please add proper release template for this 

https://release.spryker.com/templates/index-core?module=GitHook

2019-06-14 08:51 UTC, dereuromark commented
Since we dont release this (merge only), I think only the mergeonly label is missing IMO.

2019-06-14 08:59 UTC, alex-galych approved these changes

2019-06-14 08:59 UTC, merged